# extrinsic_R_IinA: [ 1, 0, 0, 0, 1, 0, 0, 0, 1 ]
# extrinsic_R_AinV: [ 1, 0, 0, 0, 1, 0, 0, 0, 1 ]
# extrinsic_T_IinA: [ 0, 0, 0 ]
# extrinsic_T_AinV: [ 0, 0, 0 ]

# base_link_frame: "base_link"
# axis_frame: "axis_link"
# lio_frame: "lio_link"
apm_bridge:
  ros__parameters:
    gravity_const: 9.801
    mass: 2.05

    lipo_cells: 6
    voltage_compensation: true

    simulation: true

    motor_parameters:
      A:  0.0000793607
      B: -0.004194295
      C:  0.104836283
      D: -0.231665421
      n:  4

    init_position:
      altitude: 100.0
      latitude: 40.0422820
      longitude: 116.3714300
